### ISSUE TITLE
Push release tarballs to official website

### ISSUE THREAD

**Issue by EvaSDK** [01org/dleyna-connector-dbus#13]
Hi there,

it seems most distros missed the release since it is not available on the 01.org website. Would it be possible to get them there or do you intend to stick with github's autogenerated archives for now ?

**Comment by rsbells** [comment]
I have updated both dleyna-linux and o1.org webstite...

**Comment by EvaSDK** [comment]
Found the entry in the downloads section. I wonder if I simply missed it or if the website was not up-to-date when I visited it as the look is sure different. Thanks anyway.
